import { Inter } from "next/font/google";
import { Assistant } from "next/font/google";
import "./globals.css";

const assistant = Assistant({
  subsets: ["latin"],
  weight: ["300", "400", "600", "500", "700"],
  variable: "--font-assistant",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={assistant.variable}>
      <body className="font-assistant">{children}</body>
    </html>
  );
}
